@startuml
left to right direction

actor Клиент
actor Кассир
actor Мойщик
actor Директор

rectangle "Система Автомойка" {
  (Зарегистрироваться по номеру телефона) as UC001
  (Добавить автомобиль в профиль) as UC002
  (Просмотреть список доступных моек) as UC003
  (Просмотреть услуги и цены) as UC004
  (Просмотреть свободное время) as UC005
  (Создать запись на мойку) as UC006
  (Просмотреть свои записи) as UC007
  (Отменить запись) as UC008
  
  (Найти клиента по номеру телефона) as UC009
  (Создать запись для клиента без приложения) as UC010
  (Просмотреть текущие записи) as UC011
  (Отметить оплату услуг) as UC012
  (Управлять статусами записей) as UC013
  
  (Просмотреть задачи на день) as UC014
  (Отметить начало работы) as UC015
  (Отметить завершение работы) as UC016
  (Просмотреть статистику работы) as UC017
  
  (Просмотреть ежедневную выручку) as UC018
  (Просмотреть загрузку боксов) as UC019
  (Просмотреть статистику по услугам) as UC020
  (Управлять списком моек) as UC021
  (Управлять услугами и ценами) as UC022
}

Клиент --> UC001
Клиент --> UC002
Клиент --> UC003
Клиент --> UC004
Клиент --> UC005
Клиент --> UC006
Клиент --> UC007
Клиент --> UC008

Кассир --> UC009
Кассир --> UC010
Кассир --> UC011
Кассир --> UC012
Кассир --> UC013

Мойщик --> UC014
Мойщик --> UC015
Мойщик --> UC016
Мойщик --> UC017

Директор --> UC018
Директор --> UC019
Директор --> UC020
Директор --> UC021
Директор --> UC022

UC003 .> UC005 : <<include>>
UC003 .> UC004 : <<include>>
UC005 .> UC006 : <<include>>
UC009 .> UC010 : <<include>>
UC011 .> UC013 : <<include>>
UC014 .> UC015 : <<extend>>
UC014 .> UC016 : <<extend>>
UC021 .> UC022 : <<include>>
@enduml